#!/usr/bin/env python3
"""
render_report.py — Render an audit report from findings.json.

Consumes the JSON output of audit_raml.py and renders it as either Markdown
or self-contained HTML. The HTML output uses neutral, accessible styling.

Usage:
    python scripts/render_report.py --findings findings.json --out report.md --format markdown
    python scripts/render_report.py --findings findings.json --out report.html --format html

Copyright (c) 2026 Karim DJAAFAR — Jasmine Conseil
Licensed under the Apache License, Version 2.0.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path
from typing import Any

# ── Severity icons (unicode, no external assets) ────────────────────────────
SEVERITY_ICON = {
    "BLOCKER": "🛑",
    "MAJOR": "⚠️",
    "MINOR": "🔵",
    "INFO": "⚪",
}

VERDICT_ICON = {
    "GO": "✅",
    "GO-WITH-RESERVATIONS": "⚠️",
    "NO-GO": "🛑",
}


# ── Markdown rendering ──────────────────────────────────────────────────────


def render_markdown(payload: dict[str, Any]) -> str:
    findings = payload["findings"]
    counts = payload["counts"]
    score = payload["score"]
    verdict = payload["verdict"]
    raml_path = payload["raml_path"]

    lines: list[str] = []
    lines.append(f"# RAML Audit Report — `{raml_path}`")
    lines.append("")
    lines.append(f"**Audited file:** `{raml_path}`  ")
    lines.append(f"**Audit date:** {date.today().isoformat()}  ")
    lines.append("**Audit standard:** MuleSoft RAML 1.0 + API-Led Connectivity best practices  ")
    lines.append("**Auditor:** `mulesoft-raml-validator` (Community Edition)")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Executive summary
    lines.append("## 1. Executive Summary")
    lines.append("")
    lines.append(f"| Metric | Value |")
    lines.append(f"|---|---|")
    lines.append(f"| **Readiness score** | **{score} / 100** |")
    lines.append(f"| **Verdict** | {VERDICT_ICON.get(verdict, '')} **{verdict}** |")
    lines.append(f"| BLOCKERs | {counts['BLOCKER']} |")
    lines.append(f"| MAJORs | {counts['MAJOR']} |")
    lines.append(f"| MINORs | {counts['MINOR']} |")
    lines.append(f"| INFOs | {counts['INFO']} |")
    lines.append(f"| Total findings | {payload['total_findings']} |")
    lines.append("")

    # Findings table
    if findings:
        lines.append("## 2. Findings Table")
        lines.append("")
        lines.append("| # | ID | Severity | Category | Location | Summary |")
        lines.append("|---|---|---|---|---|---|")
        for i, f in enumerate(findings, 1):
            icon = SEVERITY_ICON.get(f["severity"], "")
            lines.append(
                f"| {i} | `{f['rule_id']}` | {icon} {f['severity']} | "
                f"{f['category']} | {f['location']} | {f['summary']} |"
            )
        lines.append("")

        # Detailed findings
        lines.append("## 3. Detailed Findings")
        lines.append("")
        for f in findings:
            icon = SEVERITY_ICON.get(f["severity"], "")
            lines.append(f"### {icon} {f['severity']} — `{f['rule_id']}` · {f['summary']}")
            lines.append("")
            lines.append(f"**Location:** {f['location']}  ")
            lines.append(f"**Category:** {f['category']}")
            lines.append("")
            lines.append(f["detail"])
            lines.append("")
            lines.append("**Remediation:**")
            lines.append("")
            lines.append("```yaml")
            lines.append(f["remediation"])
            lines.append("```")
            lines.append("")
            lines.append("---")
            lines.append("")
    else:
        lines.append("## 2. Findings")
        lines.append("")
        lines.append("✅ No findings — the spec passes all 23 audit rules.")
        lines.append("")

    # Score appendix
    lines.append("## 4. Score Calculation")
    lines.append("")
    lines.append("Starting at 100, applying weights: -15/BLOCKER, -5/MAJOR, -2/MINOR, 0/INFO.")
    lines.append("")
    lines.append("| Severity | Count | Weight | Subtotal |")
    lines.append("|---|---|---|---|")
    lines.append(f"| BLOCKER | {counts['BLOCKER']} | -15 | {counts['BLOCKER'] * -15} |")
    lines.append(f"| MAJOR | {counts['MAJOR']} | -5 | {counts['MAJOR'] * -5} |")
    lines.append(f"| MINOR | {counts['MINOR']} | -2 | {counts['MINOR'] * -2} |")
    lines.append(f"| INFO | {counts['INFO']} | 0 | 0 |")
    lines.append("")
    lines.append(f"**Final score: {score} / 100 — Verdict: {verdict}.**")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(
        "*Report generated by [`mulesoft-raml-validator`](https://github.com/karim-djaafar/mulesoft-raml-validator) "
        "(Community Edition, Apache 2.0).*"
    )

    return "\n".join(lines)


# ── HTML rendering ──────────────────────────────────────────────────────────

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>RAML Audit Report — {raml_path}</title>
<style>
  :root {{
    --bg: #fafafa; --fg: #1a1a1a; --muted: #666;
    --border: #e0e0e0; --accent: #0066cc;
    --blocker: #d32f2f; --major: #f57c00; --minor: #1976d2; --info: #757575;
    --code-bg: #f4f4f4;
  }}
  * {{ box-sizing: border-box; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
    background: var(--bg); color: var(--fg); line-height: 1.6;
    max-width: 960px; margin: 2rem auto; padding: 0 1.5rem;
  }}
  h1 {{ border-bottom: 3px solid var(--accent); padding-bottom: 0.5rem; }}
  h2 {{ border-bottom: 1px solid var(--border); padding-bottom: 0.3rem; margin-top: 2.5rem; }}
  h3 {{ margin-top: 2rem; }}
  table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; font-size: 0.92rem; }}
  th, td {{ border: 1px solid var(--border); padding: 0.5rem 0.75rem; text-align: left; vertical-align: top; }}
  th {{ background: #f0f0f0; font-weight: 600; }}
  tr:nth-child(even) {{ background: #fafafa; }}
  pre {{
    background: var(--code-bg); border: 1px solid var(--border);
    padding: 1rem; overflow-x: auto; border-radius: 4px; font-size: 0.88rem;
  }}
  code {{ background: var(--code-bg); padding: 0.1em 0.35em; border-radius: 3px; font-size: 0.92em; }}
  pre code {{ background: none; padding: 0; }}
  .badge {{
    display: inline-block; padding: 0.15rem 0.6rem; border-radius: 12px;
    font-size: 0.78rem; font-weight: 600; color: white;
  }}
  .badge-blocker {{ background: var(--blocker); }}
  .badge-major {{ background: var(--major); }}
  .badge-minor {{ background: var(--minor); }}
  .badge-info {{ background: var(--info); }}
  .score-card {{
    background: white; border: 2px solid var(--accent); border-radius: 8px;
    padding: 1.5rem; margin: 1.5rem 0; text-align: center;
  }}
  .score-value {{ font-size: 3rem; font-weight: 700; color: var(--accent); }}
  .verdict {{ font-size: 1.3rem; margin-top: 0.5rem; }}
  .verdict-go {{ color: #2e7d32; }}
  .verdict-reservations {{ color: var(--major); }}
  .verdict-nogo {{ color: var(--blocker); }}
  .finding {{
    background: white; border-left: 4px solid var(--border);
    padding: 1rem 1.25rem; margin: 1.25rem 0; border-radius: 0 4px 4px 0;
  }}
  .finding-blocker {{ border-left-color: var(--blocker); }}
  .finding-major {{ border-left-color: var(--major); }}
  .finding-minor {{ border-left-color: var(--minor); }}
  .finding-info {{ border-left-color: var(--info); }}
  .meta {{ color: var(--muted); font-size: 0.9rem; }}
  footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border);
            color: var(--muted); font-size: 0.85rem; text-align: center; }}
</style>
</head>
<body>
<h1>RAML Audit Report</h1>
<p class="meta">
  <strong>Audited file:</strong> <code>{raml_path}</code><br>
  <strong>Audit date:</strong> {date}<br>
  <strong>Standard:</strong> MuleSoft RAML 1.0 + API-Led Connectivity best practices
</p>

<div class="score-card">
  <div class="score-value">{score} / 100</div>
  <div class="verdict verdict-{verdict_class}">{verdict_icon} {verdict}</div>
</div>

<h2>Findings Summary</h2>
<table>
<tr><th>Severity</th><th>Count</th></tr>
<tr><td><span class="badge badge-blocker">BLOCKER</span></td><td>{blocker_count}</td></tr>
<tr><td><span class="badge badge-major">MAJOR</span></td><td>{major_count}</td></tr>
<tr><td><span class="badge badge-minor">MINOR</span></td><td>{minor_count}</td></tr>
<tr><td><span class="badge badge-info">INFO</span></td><td>{info_count}</td></tr>
<tr><td><strong>Total</strong></td><td><strong>{total_count}</strong></td></tr>
</table>

<h2>Detailed Findings</h2>
{findings_html}

<footer>
Generated by <a href="https://github.com/karim-djaafar/mulesoft-raml-validator">mulesoft-raml-validator</a>
(Community Edition, Apache 2.0)
</footer>
</body>
</html>
"""


def html_escape(text: str) -> str:
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def render_finding_html(f: dict[str, Any]) -> str:
    sev_class = f["severity"].lower()
    return f"""
<div class="finding finding-{sev_class}">
  <h3>
    <span class="badge badge-{sev_class}">{f['severity']}</span>
    <code>{html_escape(f['rule_id'])}</code> · {html_escape(f['summary'])}
  </h3>
  <p class="meta">
    <strong>Location:</strong> {html_escape(f['location'])} · 
    <strong>Category:</strong> {html_escape(f['category'])}
  </p>
  <p>{html_escape(f['detail'])}</p>
  <p><strong>Remediation:</strong></p>
  <pre><code>{html_escape(f['remediation'])}</code></pre>
</div>
"""


def render_html(payload: dict[str, Any]) -> str:
    counts = payload["counts"]
    verdict = payload["verdict"]
    verdict_class_map = {
        "GO": "go",
        "GO-WITH-RESERVATIONS": "reservations",
        "NO-GO": "nogo",
    }
    findings_html = (
        "\n".join(render_finding_html(f) for f in payload["findings"])
        if payload["findings"]
        else "<p>✅ No findings — the spec passes all 23 audit rules.</p>"
    )
    return HTML_TEMPLATE.format(
        raml_path=html_escape(payload["raml_path"]),
        date=date.today().isoformat(),
        score=payload["score"],
        verdict=verdict,
        verdict_class=verdict_class_map.get(verdict, "nogo"),
        verdict_icon=VERDICT_ICON.get(verdict, ""),
        blocker_count=counts["BLOCKER"],
        major_count=counts["MAJOR"],
        minor_count=counts["MINOR"],
        info_count=counts["INFO"],
        total_count=payload["total_findings"],
        findings_html=findings_html,
    )


# ── CLI ─────────────────────────────────────────────────────────────────────


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Render an audit report from findings.json."
    )
    parser.add_argument("--findings", type=Path, required=True, help="Path to findings.json.")
    parser.add_argument("--out", type=Path, required=True, help="Output file path.")
    parser.add_argument(
        "--format",
        choices=("markdown", "html"),
        default="markdown",
        help="Output format (default: markdown).",
    )
    args = parser.parse_args()

    try:
        payload = json.loads(args.findings.read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError) as exc:
        sys.stderr.write(f"ERROR: cannot read findings: {exc}\n")
        return 1

    if args.format == "markdown":
        output = render_markdown(payload)
    else:
        output = render_html(payload)

    args.out.write_text(output, encoding="utf-8")
    sys.stdout.write(f"✓ Report rendered: {args.out} ({args.format})\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
